global using FluentValidation;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.DependencyInjection;
global using BuildingBlocks.CQRS.Command;
global using Identity.Application.Services;
global using Identity.Application.IServices;
global using BuildingBlocks.Helpers;
global using Identity.Domain.Entites;
global using BuildingBlocks.Exceptions;
