services:
  redis:
    image: redis

  productsdb:
    image: postgres
      
  products.api:
    image: ${DOCKER_REGISTRY-}productsapi
    build:
      context: .
      dockerfile: Services/Products/Products.API/Dockerfile
  
  identitydb:
    image: mcr.microsoft.com/mssql/server

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

volumes:
  products_postgresDb:
  identity_mssqlDb:
  redis_data:

