services:
  productsdb:
    container_name: productsdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ProductsDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - products_postgresDb:/var/lib/postgresql/data

  products.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Products=Server=productsdb;Port=5432;Database=ProductsDb;User Id=postgres;Password=postgres;
    depends_on:
      - productsdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  identitydb:
    container_name: identitydb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password@SqlServer123
      - MSSQL_PID=Developer
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - identity_mssqlDb:/var/opt/mssql
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Identity=Server=identitydb,1433;Database=master;User ID=sa;Password=Password@SqlServer123;Encrypt=True;TrustServerCertificate=True;
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
